#!/usr/bin/python3

from scripts.bootstrap import Bootstrap


def main():
    bootstrap = Bootstrap(
        verbose=2,
        mode="mlmodel",
        save_scored=True
    )
    bootstrap.use_dummy_sequence()
    bootstrap.run()


if __name__ == "__main__":
    main()
