#!/usr/bin/python3
import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from scripts.machine_learning import DecisionTreeActor

with open("./mapping.json", 'r') as f:
    mapping = json.loads(f.read())


def main():
    actor = DecisionTreeActor(
        dataset_dir="./datasets",
        sample_dir="./samples",
        models_dir="./models",
        model_path="./model.pkl",
        mapping=mapping,
        mode="ALL",
        drop_empty_keys=True,
        model=KNeighborsClassifier() # SVC(C=1.0, kernel='rbf', gamma='scale')
    )
    # actor.samples_to_dataset("dataset.json")
    actor.samples_to_database()
    actor.read_dataset("dataset.db")
    actor.train_test_split()
    actor.train()
    accuracy = actor.evaluate()
    print(accuracy)
    actor.save_model("model.pkl")


if __name__ == "__main__":
    main()
