#!/usr/bin/python3

import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from scripts.machine_learning import MLClassifier
from scripts.ann import RNNClassifier


def main():
    actor = RNNClassifier(
        mapping_path='./mapping.json',
        mode="ALL",
        drop_empty_keys=False
    )
    # actor.load('./models/model.h5')
    actor.samples_to_database()
    actor.read_dataset()
    actor.train_test_split()
    actor.fit()
#     accuracy = actor.evaluate()
#     print(accuracy)
    actor.save("./models/model.h5")


if __name__ == "__main__":
    main()
